### ISSUE TITLE
token_file for controlled data

### ISSUE THREAD

**Issue by WeijiaSu** [abdohlman/tcma_code#1]
Hello,

I am trying to reproduce the code to download some TCGA raw reads data and/or bam files. I see there a parameter called $token_file, I was wondering how to get this tocken_file to get the access to the controlled data?

Thanks for your help.
Weijia

**Comment by abdohlman** [comment]
Hello! To get a token file you need to apply for access through [dbGap](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000178.v11.p8). Once you've done so, you'll log in to your NIH account from the GDC portal. Then click your username on the top ribbon and select "Download Token" from the dropdown menu.
